INSERT INTO styles_music(name_style) VALUES('Rock');
INSERT INTO styles_music(name_style) VALUES('Pop');
INSERT INTO styles_music(name_style) VALUES('Rap');
INSERT INTO musicians (alias) VALUES('Elvis Presley');
INSERT INTO musicians (alias) VALUES('Sex Pistols');
INSERT INTO musicians (alias) VALUES('Billie Eilish');
INSERT INTO musicians (alias) VALUES('Anacondaz');
INSERT INTO styles_musicians (id_musician, id_style_music) VALUES (1, 1);
INSERT INTO styles_musicians (id_musician, id_style_music) VALUES (2, 1);
INSERT INTO styles_musicians (id_musician, id_style_music) VALUES (3, 2);
INSERT INTO styles_musicians (id_musician, id_style_music) VALUES (4, 1), (4, 3);
INSERT INTO albums (name_album, release_yaer) VALUES('album Elvis Presley', 2000);
INSERT INTO albums (name_album, release_yaer) VALUES('album Sex Pistols', 2010);
INSERT INTO albums (name_album, release_yaer) VALUES('album Billie Eilish', 2020);
INSERT INTO albums (name_album, release_yaer) VALUES('album Anacondaz', 2023);
INSERT INTO albums_musicians (id_album, id_musician) VALUES (1, 1);
INSERT INTO albums_musicians (id_album, id_musician) VALUES (2, 2);
INSERT INTO albums_musicians (id_album, id_musician) VALUES (3, 3);
INSERT INTO albums_musicians (id_album, id_musician) VALUES (4, 4);
INSERT INTO tracks (name_track, duration, album) VALUES ('track_1_Elvis Presley', '00:04:45', 1);
INSERT INTO tracks (name_track, duration, album) VALUES ('track_2_Elvis Presley', '00:03:37', 1);
INSERT INTO tracks (name_track, duration, album) VALUES ('track_1_Sex Pistols', '00:03:12', 2);
INSERT INTO tracks (name_track, duration, album) VALUES ('track_2_Sex Pistols', '00:03:54', 2);
INSERT INTO tracks (name_track, duration, album) VALUES ('track_1_Billie Eilish', '00:03:39', 3);
INSERT INTO tracks (name_track, duration, album) VALUES ('track_2_Billie Eilish', '00:02:57', 3);
INSERT INTO tracks (name_track, duration, album) VALUES ('track_1_Anacondaz', '00:04:49', 4);
INSERT INTO tracks (name_track, duration, album) VALUES ('track_2_Anacondaz', '00:03:23', 4);
INSERT INTO collections (name_collection, release_yaer) VALUES ('collections_1', 2000);
INSERT INTO collections (name_collection, release_yaer) VALUES ('collections_2', 2010);
INSERT INTO collections (name_collection, release_yaer) VALUES ('collections_3', 2015);
INSERT INTO collections (name_collection, release_yaer) VALUES ('collections_4', 2023);
INSERT INTO tracks_collections (id_collection, id_track) VALUES (1, 2), (1, 6);
INSERT INTO tracks_collections (id_collection, id_track) VALUES (2, 3), (2, 4);
INSERT INTO tracks_collections (id_collection, id_track) VALUES (3, 1), (3, 7);
INSERT INTO tracks_collections (id_collection, id_track) VALUES (4, 5), (4, 8);